export const STORAGE_KEY = 'product_reviews'
export const VOTES_STORAGE_KEY = 'product_review_votes'
export const PAGE_SIZE = 10
export const MAX_IMAGES = 3

export const SORT_OPTIONS = {
  NEWEST: 'newest',
  OLDEST: 'oldest',
  MOST_USEFUL: 'most_useful',
}

export const FILTER_RATINGS = {
  ALL: 'all',
  FIVE: 5,
  FOUR: 4,
  THREE: 3,
  TWO: 2,
  ONE: 1,
}

export const CURRENT_USER = 'user_current'
export const MERCHANT_USER = 'merchant'

const BASE_TIME = Date.now() - 86400000 * 7

export const MOCK_REVIEWS = [
  {
    id: 'r_001',
    userId: 'user_1',
    username: '小明同学',
    rating: 5,
    content: '商品质量非常好，包装精美，物流也很快，完全超出预期！会继续回购的。',
    images: [],
    createdAt: BASE_TIME + 3600000 * 2,
    usefulCount: 12,
    uselessCount: 1,
    followUps: [
      {
        id: 'f_001',
        content: '用了一周后来追评，真的很耐用，性价比很高！',
        createdAt: BASE_TIME + 86400000 * 2,
      },
    ],
    merchantReply: {
      content: '感谢您的好评！我们会继续努力为您提供更好的商品和服务。',
      createdAt: BASE_TIME + 3600000 * 5,
    },
  },
  {
    id: 'r_002',
    userId: 'user_2',
    username: '爱购物的猫',
    rating: 4,
    content: '整体还不错，细节上还有提升空间，不过这个价格已经很划算了。',
    images: [],
    createdAt: BASE_TIME + 3600000 * 10,
    usefulCount: 5,
    uselessCount: 0,
    followUps: [],
    merchantReply: null,
  },
  {
    id: 'r_003',
    userId: 'user_3',
    username: '数码发烧友',
    rating: 5,
    content: '做工精细，手感一流，功能齐全，非常满意的一次购物体验！',
    images: [],
    createdAt: BASE_TIME + 86400000,
    usefulCount: 23,
    uselessCount: 2,
    followUps: [],
    merchantReply: {
      content: '感谢支持！期待您的再次光临。',
      createdAt: BASE_TIME + 86400000 + 7200000,
    },
  },
  {
    id: 'r_004',
    userId: 'user_4',
    username: '平凡的一天',
    rating: 3,
    content: '东西一般般吧，没有想象中那么好，但也不算差，中规中矩。',
    images: [],
    createdAt: BASE_TIME + 86400000 * 2,
    usefulCount: 3,
    uselessCount: 4,
    followUps: [],
    merchantReply: null,
  },
  {
    id: 'r_005',
    userId: 'user_5',
    username: '柠檬不萌',
    rating: 2,
    content: '收到后有点小失望，和图片有差距，希望能改进。',
    images: [],
    createdAt: BASE_TIME + 86400000 * 3,
    usefulCount: 2,
    uselessCount: 1,
    followUps: [],
    merchantReply: {
      content: '非常抱歉给您带来不好的体验，我们已将您的反馈转达给相关部门，如有问题请联系客服处理。',
      createdAt: BASE_TIME + 86400000 * 3 + 3600000,
    },
  },
  {
    id: 'r_006',
    userId: 'user_6',
    username: '快乐星球',
    rating: 1,
    content: '不太满意，和描述的不太一样，已经申请退款了。',
    images: [],
    createdAt: BASE_TIME + 86400000 * 4,
    usefulCount: 6,
    uselessCount: 0,
    followUps: [],
    merchantReply: null,
  },
  {
    id: 'r_007',
    userId: 'user_7',
    username: '阳光明媚',
    rating: 5,
    content: '超级棒！朋友看到都问我在哪里买的，已经推荐给他们了~',
    images: [],
    createdAt: BASE_TIME + 86400000 * 4 + 3600000 * 5,
    usefulCount: 18,
    uselessCount: 0,
    followUps: [
      {
        id: 'f_002',
        content: '今天朋友也下单了，说收到也很满意！',
        createdAt: BASE_TIME + 86400000 * 5,
      },
      {
        id: 'f_003',
        content: '用了这么久还是很喜欢，值得购买！',
        createdAt: BASE_TIME + 86400000 * 6,
      },
    ],
    merchantReply: null,
  },
  {
    id: 'r_008',
    userId: 'user_8',
    username: '夜色温柔',
    rating: 4,
    content: '发货速度快，包装严实，商品和描述基本一致，好评。',
    images: [],
    createdAt: BASE_TIME + 86400000 * 5,
    usefulCount: 8,
    uselessCount: 0,
    followUps: [],
    merchantReply: null,
  },
  {
    id: 'r_009',
    userId: 'user_9',
    username: '清风徐来',
    rating: 5,
    content: '性价比超高，这个价位能买到这样的东西真的很惊喜！',
    images: [],
    createdAt: BASE_TIME + 86400000 * 5 + 3600000 * 8,
    usefulCount: 15,
    uselessCount: 1,
    followUps: [],
    merchantReply: null,
  },
  {
    id: 'r_010',
    userId: 'user_10',
    username: '花开半夏',
    rating: 4,
    content: '整体满意，就是物流稍微慢了一点，其他都很好。',
    images: [],
    createdAt: BASE_TIME + 86400000 * 6,
    usefulCount: 4,
    uselessCount: 0,
    followUps: [],
    merchantReply: null,
  },
  {
    id: 'r_011',
    userId: 'user_11',
    username: '云淡风轻',
    rating: 5,
    content: '第二次购买了，一如既往的好，老顾客了值得信赖。',
    images: [],
    createdAt: BASE_TIME + 86400000 * 6 + 3600000 * 3,
    usefulCount: 9,
    uselessCount: 0,
    followUps: [],
    merchantReply: null,
  },
  {
    id: 'r_012',
    userId: 'user_12',
    username: '似水年华',
    rating: 3,
    content: '还行吧，看个人喜好，我觉得还行，朋友觉得一般。',
    images: [],
    createdAt: BASE_TIME + 86400000 * 6 + 3600000 * 6,
    usefulCount: 1,
    uselessCount: 2,
    followUps: [],
    merchantReply: null,
  },
]
