export const STORAGE_KEY_LOGS = 'key-tester-logs'
export const STORAGE_KEY_FREQUENCY = 'key-tester-frequency'
export const STORAGE_KEY_LAYOUT = 'key-tester-layout'

export const MAX_LOG_ENTRIES = 100

export const KEY_WIDTHS = {
  normal: 1,
  wide: 1.5,
  wider: 1.75,
  widest: 2.25,
  spacebar: 6.25,
  tab: 1.5,
  capslock: 1.75,
  shiftLeft: 2.25,
  shiftRight: 2.75,
  ctrl: 1.25,
  win: 1.25,
  alt: 1.25,
  altGr: 1.5,
  backspace: 2,
  enter: 2.25,
  functionKey: 1,
  arrow: 1,
}

export const MODIFIER_KEYS = ['ControlLeft', 'ControlRight', 'ShiftLeft', 'ShiftRight', 'AltLeft', 'AltRight', 'MetaLeft', 'MetaRight']

export const MODIFIER_KEY_LABELS = {
  ControlLeft: 'Ctrl',
  ControlRight: 'Ctrl',
  ShiftLeft: 'Shift',
  ShiftRight: 'Shift',
  AltLeft: 'Alt',
  AltRight: 'Alt',
  MetaLeft: 'Win',
  MetaRight: 'Win',
}

export const PRESET_COMBINATIONS = [
  { keys: ['ControlLeft', 'KeyC'], label: 'Ctrl+C', description: '复制', category: 'edit' },
  { keys: ['ControlLeft', 'KeyV'], label: 'Ctrl+V', description: '粘贴', category: 'edit' },
  { keys: ['ControlLeft', 'KeyX'], label: 'Ctrl+X', description: '剪切', category: 'edit' },
  { keys: ['ControlLeft', 'KeyZ'], label: 'Ctrl+Z', description: '撤销', category: 'edit' },
  { keys: ['ControlLeft', 'KeyY'], label: 'Ctrl+Y', description: '重做', category: 'edit' },
  { keys: ['ControlLeft', 'KeyA'], label: 'Ctrl+A', description: '全选', category: 'edit' },
  { keys: ['ControlLeft', 'KeyS'], label: 'Ctrl+S', description: '保存', category: 'file' },
  { keys: ['ControlLeft', 'KeyO'], label: 'Ctrl+O', description: '打开', category: 'file' },
  { keys: ['ControlLeft', 'KeyN'], label: 'Ctrl+N', description: '新建', category: 'file' },
  { keys: ['ControlLeft', 'KeyW'], label: 'Ctrl+W', description: '关闭', category: 'file' },
  { keys: ['ControlLeft', 'KeyP'], label: 'Ctrl+P', description: '打印', category: 'file' },
  { keys: ['ControlLeft', 'KeyF'], label: 'Ctrl+F', description: '查找', category: 'nav' },
  { keys: ['ControlLeft', 'KeyH'], label: 'Ctrl+H', description: '替换', category: 'nav' },
  { keys: ['ControlLeft', 'KeyT'], label: 'Ctrl+T', description: '新标签页', category: 'browser' },
  { keys: ['ControlLeft', 'ShiftLeft', 'KeyN'], label: 'Ctrl+Shift+N', description: '新建无痕窗口', category: 'browser' },
  { keys: ['ControlLeft', 'ShiftLeft', 'KeyT'], label: 'Ctrl+Shift+T', description: '恢复关闭的标签', category: 'browser' },
  { keys: ['AltLeft', 'Tab'], label: 'Alt+Tab', description: '切换窗口', category: 'system' },
  { keys: ['AltLeft', 'F4'], label: 'Alt+F4', description: '关闭窗口', category: 'system' },
  { keys: ['ControlLeft', 'ShiftLeft', 'Escape'], label: 'Ctrl+Shift+Esc', description: '打开任务管理器', category: 'system' },
  { keys: ['MetaLeft', 'KeyE'], label: 'Win+E', description: '打开文件资源管理器', category: 'windows' },
  { keys: ['MetaLeft', 'KeyD'], label: 'Win+D', description: '显示桌面', category: 'windows' },
  { keys: ['MetaLeft', 'KeyL'], label: 'Win+L', description: '锁定电脑', category: 'windows' },
  { keys: ['MetaLeft', 'KeyR'], label: 'Win+R', description: '运行对话框', category: 'windows' },
  { keys: ['MetaLeft', 'Tab'], label: 'Win+Tab', description: '任务视图', category: 'windows' },
  { keys: ['MetaLeft', 'Space'], label: 'Cmd+Space', description: 'Spotlight 搜索', category: 'mac' },
  { keys: ['ShiftLeft', 'Enter'], label: 'Shift+Enter', description: '软回车', category: 'edit' },
  { keys: ['ControlLeft', 'KeyB'], label: 'Ctrl+B', description: '粗体', category: 'format' },
  { keys: ['ControlLeft', 'KeyI'], label: 'Ctrl+I', description: '斜体', category: 'format' },
  { keys: ['ControlLeft', 'KeyU'], label: 'Ctrl+U', description: '下划线', category: 'format' },
]

function createKey(code, label, width = KEY_WIDTHS.normal) {
  return { code, label, width }
}

export const KEYBOARD_LAYOUTS = {
  qwerty: {
    name: 'QWERTY',
    description: '美式标准键盘',
    rows: [
      [
        createKey('Escape', 'Esc'),
        createKey('F1', 'F1', KEY_WIDTHS.functionKey),
        createKey('F2', 'F2', KEY_WIDTHS.functionKey),
        createKey('F3', 'F3', KEY_WIDTHS.functionKey),
        createKey('F4', 'F4', KEY_WIDTHS.functionKey),
        createKey('F5', 'F5', KEY_WIDTHS.functionKey),
        createKey('F6', 'F6', KEY_WIDTHS.functionKey),
        createKey('F7', 'F7', KEY_WIDTHS.functionKey),
        createKey('F8', 'F8', KEY_WIDTHS.functionKey),
        createKey('F9', 'F9', KEY_WIDTHS.functionKey),
        createKey('F10', 'F10', KEY_WIDTHS.functionKey),
        createKey('F11', 'F11', KEY_WIDTHS.functionKey),
        createKey('F12', 'F12', KEY_WIDTHS.functionKey),
      ],
      [
        createKey('Backquote', '`'),
        createKey('Digit1', '1'),
        createKey('Digit2', '2'),
        createKey('Digit3', '3'),
        createKey('Digit4', '4'),
        createKey('Digit5', '5'),
        createKey('Digit6', '6'),
        createKey('Digit7', '7'),
        createKey('Digit8', '8'),
        createKey('Digit9', '9'),
        createKey('Digit0', '0'),
        createKey('Minus', '-'),
        createKey('Equal', '='),
        createKey('Backspace', 'Backspace', KEY_WIDTHS.backspace),
      ],
      [
        createKey('Tab', 'Tab', KEY_WIDTHS.tab),
        createKey('KeyQ', 'Q'),
        createKey('KeyW', 'W'),
        createKey('KeyE', 'E'),
        createKey('KeyR', 'R'),
        createKey('KeyT', 'T'),
        createKey('KeyY', 'Y'),
        createKey('KeyU', 'U'),
        createKey('KeyI', 'I'),
        createKey('KeyO', 'O'),
        createKey('KeyP', 'P'),
        createKey('BracketLeft', '['),
        createKey('BracketRight', ']'),
        createKey('Backslash', '\\'),
      ],
      [
        createKey('CapsLock', 'Caps Lock', KEY_WIDTHS.capslock),
        createKey('KeyA', 'A'),
        createKey('KeyS', 'S'),
        createKey('KeyD', 'D'),
        createKey('KeyF', 'F'),
        createKey('KeyG', 'G'),
        createKey('KeyH', 'H'),
        createKey('KeyJ', 'J'),
        createKey('KeyK', 'K'),
        createKey('KeyL', 'L'),
        createKey('Semicolon', ';'),
        createKey('Quote', "'"),
        createKey('Enter', 'Enter', KEY_WIDTHS.enter),
      ],
      [
        createKey('ShiftLeft', 'Shift', KEY_WIDTHS.shiftLeft),
        createKey('KeyZ', 'Z'),
        createKey('KeyX', 'X'),
        createKey('KeyC', 'C'),
        createKey('KeyV', 'V'),
        createKey('KeyB', 'B'),
        createKey('KeyN', 'N'),
        createKey('KeyM', 'M'),
        createKey('Comma', ','),
        createKey('Period', '.'),
        createKey('Slash', '/'),
        createKey('ShiftRight', 'Shift', KEY_WIDTHS.shiftRight),
      ],
      [
        createKey('ControlLeft', 'Ctrl', KEY_WIDTHS.ctrl),
        createKey('MetaLeft', 'Win', KEY_WIDTHS.win),
        createKey('AltLeft', 'Alt', KEY_WIDTHS.alt),
        createKey('Space', 'Space', KEY_WIDTHS.spacebar),
        createKey('AltRight', 'Alt', KEY_WIDTHS.alt),
        createKey('MetaRight', 'Win', KEY_WIDTHS.win),
        createKey('ArrowLeft', '←', KEY_WIDTHS.arrow),
        createKey('ArrowUp', '↑', KEY_WIDTHS.arrow),
        createKey('ArrowDown', '↓', KEY_WIDTHS.arrow),
        createKey('ArrowRight', '→', KEY_WIDTHS.arrow),
        createKey('ControlRight', 'Ctrl', KEY_WIDTHS.ctrl),
      ],
    ],
  },
  azerty: {
    name: 'AZERTY',
    description: '法式键盘',
    rows: [
      [
        createKey('Escape', 'Esc'),
        createKey('F1', 'F1', KEY_WIDTHS.functionKey),
        createKey('F2', 'F2', KEY_WIDTHS.functionKey),
        createKey('F3', 'F3', KEY_WIDTHS.functionKey),
        createKey('F4', 'F4', KEY_WIDTHS.functionKey),
        createKey('F5', 'F5', KEY_WIDTHS.functionKey),
        createKey('F6', 'F6', KEY_WIDTHS.functionKey),
        createKey('F7', 'F7', KEY_WIDTHS.functionKey),
        createKey('F8', 'F8', KEY_WIDTHS.functionKey),
        createKey('F9', 'F9', KEY_WIDTHS.functionKey),
        createKey('F10', 'F10', KEY_WIDTHS.functionKey),
        createKey('F11', 'F11', KEY_WIDTHS.functionKey),
        createKey('F12', 'F12', KEY_WIDTHS.functionKey),
      ],
      [
        createKey('Backquote', '²'),
        createKey('Digit1', '&'),
        createKey('Digit2', 'é'),
        createKey('Digit3', '"'),
        createKey('Digit4', "'"),
        createKey('Digit5', '('),
        createKey('Digit6', '-'),
        createKey('Digit7', 'è'),
        createKey('Digit8', '_'),
        createKey('Digit9', 'ç'),
        createKey('Digit0', 'à'),
        createKey('Minus', ')'),
        createKey('Equal', '='),
        createKey('Backspace', 'Backspace', KEY_WIDTHS.backspace),
      ],
      [
        createKey('Tab', 'Tab', KEY_WIDTHS.tab),
        createKey('KeyA', 'A'),
        createKey('KeyZ', 'Z'),
        createKey('KeyE', 'E'),
        createKey('KeyR', 'R'),
        createKey('KeyT', 'T'),
        createKey('KeyY', 'Y'),
        createKey('KeyU', 'U'),
        createKey('KeyI', 'I'),
        createKey('KeyO', 'O'),
        createKey('KeyP', 'P'),
        createKey('BracketLeft', '^'),
        createKey('BracketRight', '$'),
        createKey('Backslash', '*'),
      ],
      [
        createKey('CapsLock', 'Caps Lock', KEY_WIDTHS.capslock),
        createKey('KeyQ', 'Q'),
        createKey('KeyS', 'S'),
        createKey('KeyD', 'D'),
        createKey('KeyF', 'F'),
        createKey('KeyG', 'G'),
        createKey('KeyH', 'H'),
        createKey('KeyJ', 'J'),
        createKey('KeyK', 'K'),
        createKey('KeyL', 'L'),
        createKey('Semicolon', 'M'),
        createKey('Quote', 'ù'),
        createKey('Enter', 'Enter', KEY_WIDTHS.enter),
      ],
      [
        createKey('ShiftLeft', 'Shift', KEY_WIDTHS.shiftLeft),
        createKey('KeyW', 'W'),
        createKey('KeyX', 'X'),
        createKey('KeyC', 'C'),
        createKey('KeyV', 'V'),
        createKey('KeyB', 'B'),
        createKey('KeyN', 'N'),
        createKey('Comma', ','),
        createKey('Period', ';'),
        createKey('Slash', ':'),
        createKey('ShiftRight', 'Shift', KEY_WIDTHS.shiftRight),
      ],
      [
        createKey('ControlLeft', 'Ctrl', KEY_WIDTHS.ctrl),
        createKey('MetaLeft', 'Win', KEY_WIDTHS.win),
        createKey('AltLeft', 'Alt', KEY_WIDTHS.alt),
        createKey('Space', 'Space', KEY_WIDTHS.spacebar),
        createKey('AltRight', 'AltGr', KEY_WIDTHS.altGr),
        createKey('MetaRight', 'Win', KEY_WIDTHS.win),
        createKey('ArrowLeft', '←', KEY_WIDTHS.arrow),
        createKey('ArrowUp', '↑', KEY_WIDTHS.arrow),
        createKey('ArrowDown', '↓', KEY_WIDTHS.arrow),
        createKey('ArrowRight', '→', KEY_WIDTHS.arrow),
        createKey('ControlRight', 'Ctrl', KEY_WIDTHS.ctrl),
      ],
    ],
  },
  qwertz: {
    name: 'QWERTZ',
    description: '德式键盘',
    rows: [
      [
        createKey('Escape', 'Esc'),
        createKey('F1', 'F1', KEY_WIDTHS.functionKey),
        createKey('F2', 'F2', KEY_WIDTHS.functionKey),
        createKey('F3', 'F3', KEY_WIDTHS.functionKey),
        createKey('F4', 'F4', KEY_WIDTHS.functionKey),
        createKey('F5', 'F5', KEY_WIDTHS.functionKey),
        createKey('F6', 'F6', KEY_WIDTHS.functionKey),
        createKey('F7', 'F7', KEY_WIDTHS.functionKey),
        createKey('F8', 'F8', KEY_WIDTHS.functionKey),
        createKey('F9', 'F9', KEY_WIDTHS.functionKey),
        createKey('F10', 'F10', KEY_WIDTHS.functionKey),
        createKey('F11', 'F11', KEY_WIDTHS.functionKey),
        createKey('F12', 'F12', KEY_WIDTHS.functionKey),
      ],
      [
        createKey('Backquote', '^'),
        createKey('Digit1', '1'),
        createKey('Digit2', '2'),
        createKey('Digit3', '3'),
        createKey('Digit4', '4'),
        createKey('Digit5', '5'),
        createKey('Digit6', '6'),
        createKey('Digit7', '7'),
        createKey('Digit8', '8'),
        createKey('Digit9', '9'),
        createKey('Digit0', '0'),
        createKey('Minus', 'ß'),
        createKey('Equal', '´'),
        createKey('Backspace', 'Backspace', KEY_WIDTHS.backspace),
      ],
      [
        createKey('Tab', 'Tab', KEY_WIDTHS.tab),
        createKey('KeyQ', 'Q'),
        createKey('KeyW', 'W'),
        createKey('KeyE', 'E'),
        createKey('KeyR', 'R'),
        createKey('KeyT', 'T'),
        createKey('KeyZ', 'Z'),
        createKey('KeyU', 'U'),
        createKey('KeyI', 'I'),
        createKey('KeyO', 'O'),
        createKey('KeyP', 'P'),
        createKey('BracketLeft', 'ü'),
        createKey('BracketRight', '+'),
        createKey('Backslash', '#'),
      ],
      [
        createKey('CapsLock', 'Caps Lock', KEY_WIDTHS.capslock),
        createKey('KeyA', 'A'),
        createKey('KeyS', 'S'),
        createKey('KeyD', 'D'),
        createKey('KeyF', 'F'),
        createKey('KeyG', 'G'),
        createKey('KeyH', 'H'),
        createKey('KeyJ', 'J'),
        createKey('KeyK', 'K'),
        createKey('KeyL', 'L'),
        createKey('Semicolon', 'ö'),
        createKey('Quote', 'ä'),
        createKey('Enter', 'Enter', KEY_WIDTHS.enter),
      ],
      [
        createKey('ShiftLeft', 'Shift', KEY_WIDTHS.shiftLeft),
        createKey('KeyY', 'Y'),
        createKey('KeyX', 'X'),
        createKey('KeyC', 'C'),
        createKey('KeyV', 'V'),
        createKey('KeyB', 'B'),
        createKey('KeyN', 'N'),
        createKey('KeyM', 'M'),
        createKey('Comma', ','),
        createKey('Period', '.'),
        createKey('Slash', '-'),
        createKey('ShiftRight', 'Shift', KEY_WIDTHS.shiftRight),
      ],
      [
        createKey('ControlLeft', 'Ctrl', KEY_WIDTHS.ctrl),
        createKey('MetaLeft', 'Win', KEY_WIDTHS.win),
        createKey('AltLeft', 'Alt', KEY_WIDTHS.alt),
        createKey('Space', 'Space', KEY_WIDTHS.spacebar),
        createKey('AltRight', 'AltGr', KEY_WIDTHS.altGr),
        createKey('MetaRight', 'Win', KEY_WIDTHS.win),
        createKey('ArrowLeft', '←', KEY_WIDTHS.arrow),
        createKey('ArrowUp', '↑', KEY_WIDTHS.arrow),
        createKey('ArrowDown', '↓', KEY_WIDTHS.arrow),
        createKey('ArrowRight', '→', KEY_WIDTHS.arrow),
        createKey('ControlRight', 'Ctrl', KEY_WIDTHS.ctrl),
      ],
    ],
  },
}

export const COMBINATION_CATEGORY_COLORS = {
  edit: '#3498db',
  file: '#2ecc71',
  nav: '#9b59b6',
  browser: '#e67e22',
  system: '#e74c3c',
  windows: '#0078d7',
  mac: '#555555',
  format: '#1abc9c',
}
