export const CATEGORIES = ['全部', '中餐', '西餐', '日料', '快餐', '甜品', '饮品'];

export const SHOP_PRODUCTS_GROUPS = ['热销', '主食', '小吃', '饮品', '甜点'];

export const ORDER_STATUSES = {
  PLACED: 'placed',
  ACCEPTED: 'accepted',
  PICKED_UP: 'picked_up',
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
};

export const STATUS_LABELS = {
  placed: '已下单',
  accepted: '已接单',
  picked_up: '已取餐',
  delivering: '配送中',
  delivered: '已送达',
  cancelled: '已取消',
};

export const STATUS_ORDER = ['placed', 'accepted', 'picked_up', 'delivering', 'delivered'];

export const STATUS_NEXT_MAP = {
  placed: 'accepted',
  accepted: 'picked_up',
  picked_up: 'delivering',
  delivering: 'delivered',
};

export const STORAGE_KEYS = {
  CART: 'food_order_cart',
  ADDRESSES: 'food_order_addresses',
  ORDERS: 'food_order_orders',
};

export const QUICK_REMARKS = ['不要辣', '多放葱', '少油', '免打包费', '不要香菜', '少放盐', '加饭', '加辣'];

export const MAX_ADDRESSES = 5;

export const CHINA_PROVINCES = [
  '北京市',
  '上海市',
  '广东省',
  '江苏省',
  '浙江省',
  '四川省',
  '湖北省',
  '山东省',
  '河南省',
  '福建省',
  '湖南省',
  '安徽省',
  '陕西省',
  '辽宁省',
  '重庆市',
  '天津市',
  '江西省',
  '云南省',
  '贵州省',
  '黑龙江省',
];

export const SHOPS = [
  {
    id: 'shop-1',
    name: '川味居',
    category: '中餐',
    rating: 4.6,
    monthlySales: 2340,
    deliveryTime: '30-45分钟',
    minOrder: 20,
    deliveryFee: 3,
    announcement: '本店菜品均为现炒现做，请耐心等待，值得您的期待！',
    promotion: '满30减5',
    products: [
      {
        id: 'shop-1-p-1',
        name: '麻婆豆腐',
        description: '正宗川味麻婆豆腐，麻辣鲜香',
        monthlySales: 856,
        price: 22,
        group: '主食',
        specs: [{ name: '辣度', options: ['微辣', '中辣', '特辣'] }],
        specPrices: { '微辣': 22, '中辣': 22, '特辣': 24 },
      },
      {
        id: 'shop-1-p-2',
        name: '宫保鸡丁',
        description: '花生米配鸡丁，酸甜微辣',
        monthlySales: 1023,
        price: 32,
        group: '热销',
        specs: [{ name: '辣度', options: ['微辣', '中辣', '特辣'] }],
        specPrices: { '微辣': 32, '中辣': 32, '特辣': 34 },
      },
      {
        id: 'shop-1-p-3',
        name: '水煮鱼',
        description: '鲜嫩鱼片配豆芽，麻辣入味',
        monthlySales: 678,
        price: 48,
        group: '主食',
        specs: [{ name: '辣度', options: ['微辣', '中辣', '特辣'] }],
        specPrices: { '微辣': 48, '中辣': 48, '特辣': 52 },
      },
      {
        id: 'shop-1-p-4',
        name: '回锅肉',
        description: '五花肉配蒜苗，酱香浓郁',
        monthlySales: 534,
        price: 36,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-1-p-5',
        name: '酸辣土豆丝',
        description: '酸辣爽脆，开胃下饭',
        monthlySales: 912,
        price: 16,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-1-p-6',
        name: '冰粉',
        description: '手工冰粉配红糖水，清凉解辣',
        monthlySales: 445,
        price: 8,
        group: '甜点',
        specs: [{ name: '口味', options: ['红糖', '玫瑰', '桂花'] }],
        specPrices: { '红糖': 8, '玫瑰': 9, '桂花': 9 },
      },
      {
        id: 'shop-1-p-7',
        name: '米饭',
        description: '东北珍珠米，粒粒分明',
        monthlySales: 2100,
        price: 3,
        group: '主食',
        specs: [],
      },
    ],
  },
  {
    id: 'shop-2',
    name: '意面工坊',
    category: '西餐',
    rating: 4.3,
    monthlySales: 1560,
    deliveryTime: '35-50分钟',
    minOrder: 25,
    deliveryFee: 4,
    announcement: '意面现煮现做，保证口感，每日新鲜食材！',
    promotion: '满50减8',
    products: [
      {
        id: 'shop-2-p-1',
        name: '奶油培根意面',
        description: '浓郁奶油酱配烟熏培根',
        monthlySales: 678,
        price: 38,
        group: '热销',
        specs: [],
      },
      {
        id: 'shop-2-p-2',
        name: '番茄肉酱意面',
        description: '经典番茄肉酱，酸甜可口',
        monthlySales: 534,
        price: 32,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-2-p-3',
        name: '黑椒牛柳意面',
        description: '嫩滑牛柳配黑椒酱',
        monthlySales: 423,
        price: 42,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-2-p-4',
        name: '蒜香面包',
        description: '法式面包配蒜香黄油',
        monthlySales: 312,
        price: 12,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-2-p-5',
        name: '凯撒沙拉',
        description: '罗马生菜配帕玛森芝士和培根碎',
        monthlySales: 267,
        price: 28,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-2-p-6',
        name: '提拉米苏',
        description: '意式经典甜品，咖啡与可可的完美结合',
        monthlySales: 189,
        price: 22,
        group: '甜点',
        specs: [],
      },
    ],
  },
  {
    id: 'shop-3',
    name: '寿司之神',
    category: '日料',
    rating: 4.8,
    monthlySales: 890,
    deliveryTime: '40-55分钟',
    minOrder: 30,
    deliveryFee: 5,
    announcement: '每日新鲜到货海鲜，师傅手工制作，品质保证！',
    promotion: '满80减12',
    products: [
      {
        id: 'shop-3-p-1',
        name: '三文鱼刺身',
        description: '挪威进口三文鱼，鲜嫩肥美',
        monthlySales: 345,
        price: 58,
        group: '热销',
        specs: [],
      },
      {
        id: 'shop-3-p-2',
        name: '鳗鱼寿司',
        description: '炭烤鳗鱼配特制酱汁',
        monthlySales: 278,
        price: 12,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-3-p-3',
        name: '天妇罗拼盘',
        description: '虾和蔬菜天妇罗组合',
        monthlySales: 234,
        price: 42,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-3-p-4',
        name: '味噌拉面',
        description: '浓郁味噌汤底配叉烧',
        monthlySales: 456,
        price: 36,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-3-p-5',
        name: '抹茶大福',
        description: '软糯外皮配抹茶馅心',
        monthlySales: 167,
        price: 15,
        group: '甜点',
        specs: [],
      },
      {
        id: 'shop-3-p-6',
        name: '日式煎饺',
        description: '金黄酥脆，肉汁鲜美',
        monthlySales: 312,
        price: 22,
        group: '小吃',
        specs: [],
      },
    ],
  },
  {
    id: 'shop-4',
    name: '快乐汉堡',
    category: '快餐',
    rating: 4.1,
    monthlySales: 3450,
    deliveryTime: '20-35分钟',
    minOrder: 15,
    deliveryFee: 2,
    announcement: '汉堡现做现烤，薯条现炸，品质快餐！',
    promotion: '满25减3',
    products: [
      {
        id: 'shop-4-p-1',
        name: '经典牛肉堡',
        description: '安格斯牛肉饼配生菜番茄',
        monthlySales: 1230,
        price: 25,
        group: '热销',
        specs: [{ name: '规格', options: ['单层', '双层', '三层'] }],
        specPrices: { '单层': 25, '双层': 35, '三层': 45 },
      },
      {
        id: 'shop-4-p-2',
        name: '香辣鸡腿堡',
        description: '酥脆鸡腿排配辣味酱',
        monthlySales: 987,
        price: 22,
        group: '主食',
        specs: [{ name: '规格', options: ['单层', '双层'] }],
        specPrices: { '单层': 22, '双层': 32 },
      },
      {
        id: 'shop-4-p-3',
        name: '薯条',
        description: '金黄酥脆现炸薯条',
        monthlySales: 1567,
        price: 10,
        group: '小吃',
        specs: [{ name: '规格', options: ['中份', '大份', '超大份'] }],
        specPrices: { '中份': 10, '大份': 14, '超大份': 18 },
      },
      {
        id: 'shop-4-p-4',
        name: '可乐',
        description: '冰爽碳酸饮料',
        monthlySales: 2100,
        price: 6,
        group: '饮品',
        specs: [{ name: '规格', options: ['中杯', '大杯'] }],
        specPrices: { '中杯': 6, '大杯': 8 },
      },
      {
        id: 'shop-4-p-5',
        name: '鸡块',
        description: '香酥炸鸡块配蘸酱',
        monthlySales: 876,
        price: 12,
        group: '小吃',
        specs: [{ name: '规格', options: ['5块', '10块'] }],
        specPrices: { '5块': 12, '10块': 20 },
      },
      {
        id: 'shop-4-p-6',
        name: '冰淇淋',
        description: '奶香浓郁软冰淇淋',
        monthlySales: 654,
        price: 8,
        group: '甜点',
        specs: [],
      },
    ],
  },
  {
    id: 'shop-5',
    name: '甜蜜时光',
    category: '甜品',
    rating: 4.7,
    monthlySales: 1780,
    deliveryTime: '25-40分钟',
    minOrder: 18,
    deliveryFee: 3,
    announcement: '所有甜品当日制作，新鲜送达！',
    promotion: '满40减6',
    products: [
      {
        id: 'shop-5-p-1',
        name: '杨枝甘露',
        description: '芒果西柚椰汁甜品',
        monthlySales: 567,
        price: 22,
        group: '热销',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '温度', options: ['常温', '冰'] },
        ],
        specPrices: { '中杯/常温': 22, '中杯/冰': 22, '大杯/常温': 28, '大杯/冰': 28 },
      },
      {
        id: 'shop-5-p-2',
        name: '双皮奶',
        description: '传统广式双皮奶，奶香浓郁',
        monthlySales: 432,
        price: 18,
        group: '甜点',
        specs: [
          { name: '口味', options: ['原味', '红豆', '芒果'] },
          { name: '温度', options: ['热', '常温', '冰'] },
        ],
        specPrices: {
          '原味/热': 18, '原味/常温': 18, '原味/冰': 18,
          '红豆/热': 20, '红豆/常温': 20, '红豆/冰': 20,
          '芒果/热': 21, '芒果/常温': 21, '芒果/冰': 21,
        },
      },
      {
        id: 'shop-5-p-3',
        name: '芒果班戟',
        description: '薄皮包裹鲜奶油和芒果',
        monthlySales: 345,
        price: 26,
        group: '甜点',
        specs: [],
      },
      {
        id: 'shop-5-p-4',
        name: '榴莲千层',
        description: '层层酥皮配猫山王榴莲',
        monthlySales: 278,
        price: 38,
        group: '甜点',
        specs: [
          { name: '规格', options: ['小份', '大份'] },
        ],
        specPrices: { '小份': 38, '大份': 58 },
      },
      {
        id: 'shop-5-p-5',
        name: '焦糖布丁',
        description: '法式焦糖布丁，入口即化',
        monthlySales: 234,
        price: 16,
        group: '甜点',
        specs: [
          { name: '温度', options: ['常温', '冰'] },
        ],
        specPrices: { '常温': 16, '冰': 16 },
      },
      {
        id: 'shop-5-p-6',
        name: '椰汁西米露',
        description: '椰汁配Q弹西米',
        monthlySales: 189,
        price: 14,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '温度', options: ['常温', '冰'] },
        ],
        specPrices: { '中杯/常温': 14, '中杯/冰': 14, '大杯/常温': 18, '大杯/冰': 18 },
      },
    ],
  },
  {
    id: 'shop-6',
    name: '茶百道',
    category: '饮品',
    rating: 4.5,
    monthlySales: 4560,
    deliveryTime: '15-30分钟',
    minOrder: 10,
    deliveryFee: 2,
    announcement: '鲜茶现泡，好喝不贵！各类饮品任您选择！',
    promotion: '满20减3',
    products: [
      {
        id: 'shop-6-p-1',
        name: '杨枝甘露',
        description: '芒果椰汁西米经典搭配',
        monthlySales: 1567,
        price: 15,
        group: '热销',
        specs: [
          { name: '规格', options: ['中杯', '大杯', '超大杯'] },
          { name: '温度', options: ['常温', '热', '冰'] },
          { name: '甜度', options: ['全糖', '七分糖', '半糖', '三分糖', '无糖'] },
        ],
        specPrices: {
          '中杯/常温/全糖': 15, '中杯/常温/七分糖': 15, '中杯/常温/半糖': 15, '中杯/常温/三分糖': 15, '中杯/常温/无糖': 15,
          '中杯/热/全糖': 15, '中杯/热/七分糖': 15, '中杯/热/半糖': 15, '中杯/热/三分糖': 15, '中杯/热/无糖': 15,
          '中杯/冰/全糖': 16, '中杯/冰/七分糖': 16, '中杯/冰/半糖': 16, '中杯/冰/三分糖': 16, '中杯/冰/无糖': 16,
          '大杯/常温/全糖': 19, '大杯/常温/七分糖': 19, '大杯/常温/半糖': 19, '大杯/常温/三分糖': 19, '大杯/常温/无糖': 19,
          '大杯/热/全糖': 19, '大杯/热/七分糖': 19, '大杯/热/半糖': 19, '大杯/热/三分糖': 19, '大杯/热/无糖': 19,
          '大杯/冰/全糖': 20, '大杯/冰/七分糖': 20, '大杯/冰/半糖': 20, '大杯/冰/三分糖': 20, '大杯/冰/无糖': 20,
          '超大杯/常温/全糖': 23, '超大杯/常温/七分糖': 23, '超大杯/常温/半糖': 23, '超大杯/常温/三分糖': 23, '超大杯/常温/无糖': 23,
          '超大杯/热/全糖': 23, '超大杯/热/七分糖': 23, '超大杯/热/半糖': 23, '超大杯/热/三分糖': 23, '超大杯/热/无糖': 23,
          '超大杯/冰/全糖': 24, '超大杯/冰/七分糖': 24, '超大杯/冰/半糖': 24, '超大杯/冰/三分糖': 24, '超大杯/冰/无糖': 24,
        },
      },
      {
        id: 'shop-6-p-2',
        name: '茉莉奶绿',
        description: '茉莉花茶配鲜奶',
        monthlySales: 1234,
        price: 13,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯', '超大杯'] },
          { name: '温度', options: ['常温', '热', '冰'] },
          { name: '甜度', options: ['全糖', '七分糖', '半糖', '三分糖', '无糖'] },
        ],
        specPrices: {
          '中杯/常温/全糖': 13, '中杯/常温/七分糖': 13, '中杯/常温/半糖': 13, '中杯/常温/三分糖': 13, '中杯/常温/无糖': 13,
          '中杯/热/全糖': 13, '中杯/热/七分糖': 13, '中杯/热/半糖': 13, '中杯/热/三分糖': 13, '中杯/热/无糖': 13,
          '中杯/冰/全糖': 14, '中杯/冰/七分糖': 14, '中杯/冰/半糖': 14, '中杯/冰/三分糖': 14, '中杯/冰/无糖': 14,
          '大杯/常温/全糖': 17, '大杯/常温/七分糖': 17, '大杯/常温/半糖': 17, '大杯/常温/三分糖': 17, '大杯/常温/无糖': 17,
          '大杯/热/全糖': 17, '大杯/热/七分糖': 17, '大杯/热/半糖': 17, '大杯/热/三分糖': 17, '大杯/热/无糖': 17,
          '大杯/冰/全糖': 18, '大杯/冰/七分糖': 18, '大杯/冰/半糖': 18, '大杯/冰/三分糖': 18, '大杯/冰/无糖': 18,
          '超大杯/常温/全糖': 21, '超大杯/常温/七分糖': 21, '超大杯/常温/半糖': 21, '超大杯/常温/三分糖': 21, '超大杯/常温/无糖': 21,
          '超大杯/热/全糖': 21, '超大杯/热/七分糖': 21, '超大杯/热/半糖': 21, '超大杯/热/三分糖': 21, '超大杯/热/无糖': 21,
          '超大杯/冰/全糖': 22, '超大杯/冰/七分糖': 22, '超大杯/冰/半糖': 22, '超大杯/冰/三分糖': 22, '超大杯/冰/无糖': 22,
        },
      },
      {
        id: 'shop-6-p-3',
        name: '百香果双响炮',
        description: '百香果配椰果和珍珠',
        monthlySales: 890,
        price: 16,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯', '超大杯'] },
          { name: '温度', options: ['常温', '冰'] },
          { name: '甜度', options: ['全糖', '七分糖', '半糖', '三分糖'] },
        ],
        specPrices: {
          '中杯/常温/全糖': 16, '中杯/常温/七分糖': 16, '中杯/常温/半糖': 16, '中杯/常温/三分糖': 16,
          '中杯/冰/全糖': 17, '中杯/冰/七分糖': 17, '中杯/冰/半糖': 17, '中杯/冰/三分糖': 17,
          '大杯/常温/全糖': 20, '大杯/常温/七分糖': 20, '大杯/常温/半糖': 20, '大杯/常温/三分糖': 20,
          '大杯/冰/全糖': 21, '大杯/冰/七分糖': 21, '大杯/冰/半糖': 21, '大杯/冰/三分糖': 21,
          '超大杯/常温/全糖': 24, '超大杯/常温/七分糖': 24, '超大杯/常温/半糖': 24, '超大杯/常温/三分糖': 24,
          '超大杯/冰/全糖': 25, '超大杯/冰/七分糖': 25, '超大杯/冰/半糖': 25, '超大杯/冰/三分糖': 25,
        },
      },
      {
        id: 'shop-6-p-4',
        name: '西瓜啵啵',
        description: '鲜榨西瓜汁配脆波波',
        monthlySales: 678,
        price: 14,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '温度', options: ['常温', '冰'] },
          { name: '甜度', options: ['全糖', '半糖', '无糖'] },
        ],
        specPrices: {
          '中杯/常温/全糖': 14, '中杯/常温/半糖': 14, '中杯/常温/无糖': 14,
          '中杯/冰/全糖': 15, '中杯/冰/半糖': 15, '中杯/冰/无糖': 15,
          '大杯/常温/全糖': 18, '大杯/常温/半糖': 18, '大杯/常温/无糖': 18,
          '大杯/冰/全糖': 19, '大杯/冰/半糖': 19, '大杯/冰/无糖': 19,
        },
      },
      {
        id: 'shop-6-p-5',
        name: '桂花酒酿',
        description: '桂花配甜酒酿，古法饮品',
        monthlySales: 456,
        price: 12,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '温度', options: ['热', '常温', '冰'] },
        ],
        specPrices: {
          '中杯/热': 12, '中杯/常温': 12, '中杯/冰': 13,
          '大杯/热': 16, '大杯/常温': 16, '大杯/冰': 17,
        },
      },
      {
        id: 'shop-6-p-6',
        name: '烤奶',
        description: '焦糖烤奶，浓郁顺滑',
        monthlySales: 789,
        price: 14,
        group: '热销',
        specs: [
          { name: '规格', options: ['中杯', '大杯', '超大杯'] },
          { name: '温度', options: ['热', '常温', '冰'] },
          { name: '甜度', options: ['全糖', '七分糖', '半糖', '无糖'] },
        ],
        specPrices: {
          '中杯/热/全糖': 14, '中杯/热/七分糖': 14, '中杯/热/半糖': 14, '中杯/热/无糖': 14,
          '中杯/常温/全糖': 14, '中杯/常温/七分糖': 14, '中杯/常温/半糖': 14, '中杯/常温/无糖': 14,
          '中杯/冰/全糖': 15, '中杯/冰/七分糖': 15, '中杯/冰/半糖': 15, '中杯/冰/无糖': 15,
          '大杯/热/全糖': 18, '大杯/热/七分糖': 18, '大杯/热/半糖': 18, '大杯/热/无糖': 18,
          '大杯/常温/全糖': 18, '大杯/常温/七分糖': 18, '大杯/常温/半糖': 18, '大杯/常温/无糖': 18,
          '大杯/冰/全糖': 19, '大杯/冰/七分糖': 19, '大杯/冰/半糖': 19, '大杯/冰/无糖': 19,
          '超大杯/热/全糖': 22, '超大杯/热/七分糖': 22, '超大杯/热/半糖': 22, '超大杯/热/无糖': 22,
          '超大杯/常温/全糖': 22, '超大杯/常温/七分糖': 22, '超大杯/常温/半糖': 22, '超大杯/常温/无糖': 22,
          '超大杯/冰/全糖': 23, '超大杯/冰/七分糖': 23, '超大杯/冰/半糖': 23, '超大杯/冰/无糖': 23,
        },
      },
    ],
  },
  {
    id: 'shop-7',
    name: '湘菜馆',
    category: '中餐',
    rating: 4.4,
    monthlySales: 1980,
    deliveryTime: '30-45分钟',
    minOrder: 20,
    deliveryFee: 3,
    announcement: '地道湘味，辣得过瘾！新鲜食材每日采购！',
    promotion: '满35减5',
    products: [
      {
        id: 'shop-7-p-1',
        name: '剁椒鱼头',
        description: '鲜鱼头配自制剁椒，鲜辣入味',
        monthlySales: 678,
        price: 52,
        group: '热销',
        specs: [],
      },
      {
        id: 'shop-7-p-2',
        name: '小炒黄牛肉',
        description: '嫩滑黄牛肉配辣椒爆炒',
        monthlySales: 534,
        price: 42,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-7-p-3',
        name: '辣椒炒肉',
        description: '湖南经典家常菜',
        monthlySales: 789,
        price: 32,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-7-p-4',
        name: '干锅花菜',
        description: '花菜干锅，香辣脆嫩',
        monthlySales: 345,
        price: 26,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-7-p-5',
        name: '蒜蓉粉丝蒸虾',
        description: '鲜虾配蒜蓉粉丝，鲜美多汁',
        monthlySales: 267,
        price: 38,
        group: '热销',
        specs: [],
      },
    ],
  },
  {
    id: 'shop-8',
    name: '牛排屋',
    category: '西餐',
    rating: 4.6,
    monthlySales: 670,
    deliveryTime: '40-55分钟',
    minOrder: 40,
    deliveryFee: 5,
    announcement: '澳洲进口牛肉，专业牛排烹饪，品质保证！',
    promotion: '满100减15',
    products: [
      {
        id: 'shop-8-p-1',
        name: '菲力牛排',
        description: '精选牛里脊，嫩滑多汁',
        monthlySales: 234,
        price: 88,
        group: '热销',
        specs: [{ name: '熟度', options: ['三分熟', '五分熟', '七分熟', '全熟'] }],
        specPrices: { '三分熟': 88, '五分熟': 88, '七分熟': 88, '全熟': 88 },
      },
      {
        id: 'shop-8-p-2',
        name: '西冷牛排',
        description: '经典西冷，外焦里嫩',
        monthlySales: 189,
        price: 78,
        group: '主食',
        specs: [{ name: '熟度', options: ['三分熟', '五分熟', '七分熟', '全熟'] }],
        specPrices: { '三分熟': 78, '五分熟': 78, '七分熟': 78, '全熟': 78 },
      },
      {
        id: 'shop-8-p-3',
        name: 'T骨牛排',
        description: '一骨两味，西冷+菲力',
        monthlySales: 145,
        price: 108,
        group: '主食',
        specs: [{ name: '熟度', options: ['三分熟', '五分熟', '七分熟'] }],
        specPrices: { '三分熟': 108, '五分熟': 108, '七分熟': 108 },
      },
      {
        id: 'shop-8-p-4',
        name: '奶油蘑菇汤',
        description: '浓郁奶油配新鲜蘑菇',
        monthlySales: 312,
        price: 22,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-8-p-5',
        name: '巧克力熔岩蛋糕',
        description: '外酥内流心，巧克力爱好者的最爱',
        monthlySales: 267,
        price: 28,
        group: '甜点',
        specs: [],
      },
    ],
  },
  {
    id: 'shop-9',
    name: '拉面馆',
    category: '日料',
    rating: 4.3,
    monthlySales: 2340,
    deliveryTime: '25-40分钟',
    minOrder: 18,
    deliveryFee: 3,
    announcement: '日式豚骨汤底熬制8小时，浓郁鲜美！',
    promotion: '满30减4',
    products: [
      {
        id: 'shop-9-p-1',
        name: '豚骨拉面',
        description: '浓郁豚骨汤配叉烧和溏心蛋',
        monthlySales: 1234,
        price: 32,
        group: '热销',
        specs: [],
      },
      {
        id: 'shop-9-p-2',
        name: '味噌拉面',
        description: '味噌汤底配玉米和黄油',
        monthlySales: 567,
        price: 30,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-9-p-3',
        name: '酱油拉面',
        description: '清汤酱油底配笋干',
        monthlySales: 345,
        price: 28,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-9-p-4',
        name: '日式煎饺',
        description: '手工包制，底部金黄酥脆',
        monthlySales: 678,
        price: 18,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-9-p-5',
        name: '抹茶冰淇淋',
        description: '宇治抹茶味冰淇淋',
        monthlySales: 234,
        price: 12,
        group: '甜点',
        specs: [],
      },
    ],
  },
  {
    id: 'shop-10',
    name: '鸡排王',
    category: '快餐',
    rating: 4.0,
    monthlySales: 3120,
    deliveryTime: '20-30分钟',
    minOrder: 12,
    deliveryFee: 2,
    announcement: '大鸡排现炸现卖，外酥里嫩！',
    promotion: '满20减3',
    products: [
      {
        id: 'shop-10-p-1',
        name: '原味大鸡排',
        description: '经典原味，外酥里嫩',
        monthlySales: 1567,
        price: 18,
        group: '热销',
        specs: [{ name: '口味', options: ['原味', '香辣', '孜然', '梅子'] }],
        specPrices: { '原味': 18, '香辣': 18, '孜然': 18, '梅子': 19 },
      },
      {
        id: 'shop-10-p-2',
        name: '鸡腿堡',
        description: '炸鸡腿排配生菜沙拉酱',
        monthlySales: 890,
        price: 15,
        group: '主食',
        specs: [],
      },
      {
        id: 'shop-10-p-3',
        name: '盐酥鸡',
        description: '台式盐酥鸡，酥脆入味',
        monthlySales: 678,
        price: 16,
        group: '小吃',
        specs: [{ name: '口味', options: ['原味', '香辣', '蒜香'] }],
        specPrices: { '原味': 16, '香辣': 16, '蒜香': 17 },
      },
      {
        id: 'shop-10-p-4',
        name: '甘梅地瓜条',
        description: '甘梅粉配地瓜条，香甜酥脆',
        monthlySales: 456,
        price: 10,
        group: '小吃',
        specs: [],
      },
      {
        id: 'shop-10-p-5',
        name: '柠檬红茶',
        description: '现泡红茶配鲜柠檬',
        monthlySales: 567,
        price: 8,
        group: '饮品',
        specs: [{ name: '规格', options: ['中杯', '大杯'] }],
        specPrices: { '中杯': 8, '大杯': 10 },
      },
    ],
  },
  {
    id: 'shop-11',
    name: '雪冰城',
    category: '甜品',
    rating: 3.8,
    monthlySales: 2890,
    deliveryTime: '20-35分钟',
    minOrder: 8,
    deliveryFee: 2,
    announcement: '平价甜品，甜蜜每一天！',
    promotion: '满15减2',
    products: [
      {
        id: 'shop-11-p-1',
        name: '草莓雪花冰',
        description: '绵密雪花冰配新鲜草莓',
        monthlySales: 890,
        price: 16,
        group: '热销',
        specs: [
          { name: '规格', options: ['中份', '大份'] },
          { name: '温度', options: ['正常冰', '少冰'] },
        ],
        specPrices: { '中份/正常冰': 16, '中份/少冰': 16, '大份/正常冰': 22, '大份/少冰': 22 },
      },
      {
        id: 'shop-11-p-2',
        name: '芒果雪花冰',
        description: '芒果味雪花冰配芒果丁',
        monthlySales: 678,
        price: 16,
        group: '甜点',
        specs: [
          { name: '规格', options: ['中份', '大份'] },
          { name: '温度', options: ['正常冰', '少冰'] },
        ],
        specPrices: { '中份/正常冰': 16, '中份/少冰': 16, '大份/正常冰': 22, '大份/少冰': 22 },
      },
      {
        id: 'shop-11-p-3',
        name: '红豆刨冰',
        description: '传统红豆刨冰配炼乳',
        monthlySales: 456,
        price: 12,
        group: '甜点',
        specs: [],
      },
      {
        id: 'shop-11-p-4',
        name: '炒酸奶',
        description: '现炒酸奶配坚果果干',
        monthlySales: 567,
        price: 10,
        group: '甜点',
        specs: [
          { name: '口味', options: ['原味', '草莓', '芒果'] },
          { name: '温度', options: ['正常冰', '少冰'] },
        ],
        specPrices: { '原味/正常冰': 10, '原味/少冰': 10, '草莓/正常冰': 12, '草莓/少冰': 12, '芒果/正常冰': 12, '芒果/少冰': 12 },
      },
      {
        id: 'shop-11-p-5',
        name: '椰奶西米露',
        description: '椰奶配小西米，清甜可口',
        monthlySales: 345,
        price: 8,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '温度', options: ['常温', '冰'] },
        ],
        specPrices: { '中杯/常温': 8, '中杯/冰': 8, '大杯/常温': 12, '大杯/冰': 12 },
      },
    ],
  },
  {
    id: 'shop-12',
    name: '鲜榨果汁',
    category: '饮品',
    rating: 4.2,
    monthlySales: 1670,
    deliveryTime: '15-25分钟',
    minOrder: 12,
    deliveryFee: 2,
    announcement: '100%鲜榨，不加水不加糖，健康饮品首选！',
    promotion: '满25减4',
    products: [
      {
        id: 'shop-12-p-1',
        name: '鲜榨橙汁',
        description: '新鲜脐橙现榨，维C满满',
        monthlySales: 567,
        price: 16,
        group: '热销',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '糖度', options: ['原味', '微糖', '半糖'] },
        ],
        specPrices: { '中杯/原味': 16, '中杯/微糖': 16, '中杯/半糖': 16, '大杯/原味': 22, '大杯/微糖': 22, '大杯/半糖': 22 },
      },
      {
        id: 'shop-12-p-2',
        name: '鲜榨西瓜汁',
        description: '夏季消暑必备，清甜解渴',
        monthlySales: 890,
        price: 14,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '糖度', options: ['原味', '微糖'] },
        ],
        specPrices: { '中杯/原味': 14, '中杯/微糖': 14, '大杯/原味': 18, '大杯/微糖': 18 },
      },
      {
        id: 'shop-12-p-3',
        name: '鲜榨苹果汁',
        description: '红富士苹果现榨，自然甜味',
        monthlySales: 345,
        price: 15,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '糖度', options: ['原味', '微糖', '半糖'] },
        ],
        specPrices: { '中杯/原味': 15, '中杯/微糖': 15, '中杯/半糖': 15, '大杯/原味': 20, '大杯/微糖': 20, '大杯/半糖': 20 },
      },
      {
        id: 'shop-12-p-4',
        name: '胡萝卜苹果汁',
        description: '胡萝卜配苹果，营养均衡',
        monthlySales: 234,
        price: 18,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
        ],
        specPrices: { '中杯': 18, '大杯': 24 },
      },
      {
        id: 'shop-12-p-5',
        name: '芒果香蕉奶昔',
        description: '芒果香蕉配鲜奶，浓郁丝滑',
        monthlySales: 456,
        price: 22,
        group: '饮品',
        specs: [
          { name: '规格', options: ['中杯', '大杯'] },
          { name: '糖度', options: ['原味', '微糖', '半糖'] },
        ],
        specPrices: { '中杯/原味': 22, '中杯/微糖': 22, '中杯/半糖': 22, '大杯/原味': 28, '大杯/微糖': 28, '大杯/半糖': 28 },
      },
    ],
  },
];
