import { TREND_DAYS } from './constants'

export function generateMockFileTree() {
  return {
    name: 'src',
    type: 'directory',
    path: 'src',
    children: [
      {
        name: 'components',
        type: 'directory',
        path: 'src/components',
        children: [
          {
            name: 'Button',
            type: 'directory',
            path: 'src/components/Button',
            children: [
              {
                name: 'index.jsx',
                type: 'file',
                path: 'src/components/Button/index.jsx',
                coverage: { statements: 92, branches: 85, functions: 100, lines: 94 },
                uncoveredLines: [12, 28, 45, 67],
                lines: [
                  { line: 1, code: "import React from 'react'" },
                  { line: 2, code: "import './Button.css'" },
                  { line: 3, code: '' },
                  { line: 4, code: 'const Button = ({ children, onClick, variant = "primary", disabled }) => {' },
                  { line: 5, code: '  const baseClass = "btn"' },
                  { line: 6, code: '  const variantClass = `btn-${variant}`' },
                  { line: 7, code: '' },
                  { line: 8, code: '  const handleClick = (e) => {' },
                  { line: 9, code: '    if (disabled) return' },
                  { line: 10, code: '    if (onClick) onClick(e)' },
                  { line: 11, code: '  }' },
                  { line: 12, code: '' },
                  { line: 13, code: '  return (' },
                  { line: 14, code: '    <button' },
                  { line: 15, code: '      className={`${baseClass} ${variantClass}`}' },
                  { line: 16, code: '      onClick={handleClick}' },
                  { line: 17, code: '      disabled={disabled}' },
                  { line: 18, code: '    >' },
                  { line: 19, code: '      {children}' },
                  { line: 20, code: '    </button>' },
                  { line: 21, code: '  )' },
                  { line: 22, code: '}' },
                  { line: 23, code: '' },
                  { line: 24, code: 'export default Button' },
                ],
              },
              {
                name: 'Button.test.jsx',
                type: 'file',
                path: 'src/components/Button/Button.test.jsx',
                coverage: { statements: 100, branches: 100, functions: 100, lines: 100 },
                uncoveredLines: [],
                lines: [
                  { line: 1, code: "import { describe, it, expect } from 'vitest'" },
                  { line: 2, code: "import { render, screen, fireEvent } from '@testing-library/react'" },
                  { line: 3, code: "import Button from './index'" },
                  { line: 4, code: '' },
                  { line: 5, code: "describe('Button', () => {" },
                  { line: 6, code: "  it('renders children correctly', () => {" },
                  { line: 7, code: "    render(<Button>Click me</Button>)" },
                  { line: 8, code: "    expect(screen.getByText('Click me')).toBeInTheDocument()" },
                  { line: 9, code: '  })' },
                  { line: 10, code: '})' },
                ],
              },
            ],
          },
          {
            name: 'Modal',
            type: 'directory',
            path: 'src/components/Modal',
            children: [
              {
                name: 'index.jsx',
                type: 'file',
                path: 'src/components/Modal/index.jsx',
                coverage: { statements: 65, branches: 45, functions: 75, lines: 68 },
                uncoveredLines: [15, 22, 34, 41, 52, 58, 63, 71, 88, 95],
                lines: [
                  { line: 1, code: "import React, { useEffect, useRef } from 'react'" },
                  { line: 2, code: "import './Modal.css'" },
                  { line: 3, code: '' },
                  { line: 4, code: 'const Modal = ({ isOpen, onClose, title, children }) => {' },
                  { line: 5, code: "  const modalRef = useRef(null)" },
                  { line: 6, code: '' },
                  { line: 7, code: '  useEffect(() => {' },
                  { line: 8, code: '    if (isOpen) {' },
                  { line: 9, code: "      document.body.style.overflow = 'hidden'" },
                  { line: 10, code: '    } else {' },
                  { line: 11, code: "      document.body.style.overflow = 'auto'" },
                  { line: 12, code: '    }' },
                  { line: 13, code: '    return () => {' },
                  { line: 14, code: "      document.body.style.overflow = 'auto'" },
                  { line: 15, code: '    }' },
                  { line: 16, code: '  }, [isOpen])' },
                  { line: 17, code: '' },
                  { line: 18, code: "  const handleBackdropClick = (e) => {" },
                  { line: 19, code: '    if (modalRef.current && !modalRef.current.contains(e.target)) {' },
                  { line: 20, code: '      onClose()' },
                  { line: 21, code: '    }' },
                  { line: 22, code: '  }' },
                  { line: 23, code: '' },
                  { line: 24, code: '  if (!isOpen) return null' },
                  { line: 25, code: '' },
                  { line: 26, code: '  return (' },
                  { line: 27, code: '    <div className="modal-overlay" onClick={handleBackdropClick}>' },
                  { line: 28, code: '      <div className="modal-content" ref={modalRef}>' },
                  { line: 29, code: '        <div className="modal-header">' },
                  { line: 30, code: '          <h3 className="modal-title">{title}</h3>' },
                  { line: 31, code: '          <button className="modal-close" onClick={onClose}>×</button>' },
                  { line: 32, code: '        </div>' },
                  { line: 33, code: '        <div className="modal-body">{children}</div>' },
                  { line: 34, code: '      </div>' },
                  { line: 35, code: '    </div>' },
                  { line: 36, code: '  )' },
                  { line: 37, code: '}' },
                  { line: 38, code: '' },
                  { line: 39, code: 'export default Modal' },
                ],
              },
            ],
          },
          {
            name: 'Input.jsx',
            type: 'file',
            path: 'src/components/Input.jsx',
            coverage: { statements: 78, branches: 62, functions: 80, lines: 75 },
            uncoveredLines: [8, 15, 23, 29, 35],
            lines: [
              { line: 1, code: "import React from 'react'" },
              { line: 2, code: "import './Input.css'" },
              { line: 3, code: '' },
              { line: 4, code: 'const Input = ({ value, onChange, placeholder, type = "text", error }) => {' },
              { line: 5, code: '  const handleChange = (e) => {' },
              { line: 6, code: '    const val = e.target.value' },
              { line: 7, code: '    onChange(val)' },
              { line: 8, code: '  }' },
              { line: 9, code: '' },
              { line: 10, code: "  const inputClass = `input${error ? ' input-error' : ''}`" },
              { line: 11, code: '' },
              { line: 12, code: '  return (' },
              { line: 13, code: '    <div className="input-wrapper">' },
              { line: 14, code: '      <input' },
              { line: 15, code: '        type={type}' },
              { line: 16, code: '        className={inputClass}' },
              { line: 17, code: '        value={value}' },
              { line: 18, code: '        onChange={handleChange}' },
              { line: 19, code: '        placeholder={placeholder}' },
              { line: 20, code: '      />' },
              { line: 21, code: '      {error && <span className="input-error-text">{error}</span>}' },
              { line: 22, code: '    </div>' },
              { line: 23, code: '  )' },
              { line: 24, code: '}' },
              { line: 25, code: '' },
              { line: 26, code: 'export default Input' },
            ],
          },
        ],
      },
      {
        name: 'pages',
        type: 'directory',
        path: 'src/pages',
        children: [
          {
            name: 'Home',
            type: 'directory',
            path: 'src/pages/Home',
            children: [
              {
                name: 'index.jsx',
                type: 'file',
                path: 'src/pages/Home/index.jsx',
                coverage: { statements: 88, branches: 72, functions: 90, lines: 85 },
                uncoveredLines: [25, 38, 52, 67],
                lines: [
                  { line: 1, code: "import React, { useState, useEffect } from 'react'" },
                  { line: 2, code: "import './Home.css'" },
                  { line: 3, code: "import Header from '../../components/Header'" },
                  { line: 4, code: "import Footer from '../../components/Footer'" },
                  { line: 5, code: "import FeatureCard from '../../components/FeatureCard'" },
                  { line: 6, code: "import { fetchFeatures } from '../../api/features'" },
                  { line: 7, code: '' },
                  { line: 8, code: 'const Home = () => {' },
                  { line: 9, code: "  const [features, setFeatures] = useState([])" },
                  { line: 10, code: "  const [loading, setLoading] = useState(true)" },
                  { line: 11, code: "  const [error, setError] = useState(null)" },
                  { line: 12, code: '' },
                  { line: 13, code: '  useEffect(() => {' },
                  { line: 14, code: '    const loadFeatures = async () => {' },
                  { line: 15, code: '      try {' },
                  { line: 16, code: '        const data = await fetchFeatures()' },
                  { line: 17, code: '        setFeatures(data)' },
                  { line: 18, code: '      } catch (err) {' },
                  { line: 19, code: "        setError('加载失败')" },
                  { line: 20, code: '      } finally {' },
                  { line: 21, code: '        setLoading(false)' },
                  { line: 22, code: '      }' },
                  { line: 23, code: '    }' },
                  { line: 24, code: '    loadFeatures()' },
                  { line: 25, code: '  }, [])' },
                  { line: 26, code: '' },
                  { line: 27, code: '  return (' },
                  { line: 28, code: "    <div className='home-page'>" },
                  { line: 29, code: '      <Header />' },
                  { line: 30, code: '      <main className="home-main">' },
                  { line: 31, code: '        {loading && <div className="loading">加载中...</div>}' },
                  { line: 32, code: '        {error && <div className="error">{error}</div>}' },
                  { line: 33, code: '        {!loading && !error && (' },
                  { line: 34, code: '          <div className="features-grid">' },
                  { line: 35, code: '            {features.map((feature) => (' },
                  { line: 36, code: '              <FeatureCard key={feature.id} feature={feature} />' },
                  { line: 37, code: '            ))}' },
                  { line: 38, code: '          </div>' },
                  { line: 39, code: '        )}' },
                  { line: 40, code: '      </main>' },
                  { line: 41, code: '      <Footer />' },
                  { line: 42, code: '    </div>' },
                  { line: 43, code: '  )' },
                  { line: 44, code: '}' },
                  { line: 45, code: '' },
                  { line: 46, code: 'export default Home' },
                ],
              },
            ],
          },
          {
            name: 'About.jsx',
            type: 'file',
            path: 'src/pages/About.jsx',
            coverage: { statements: 100, branches: 100, functions: 100, lines: 100 },
            uncoveredLines: [],
            lines: [
              { line: 1, code: "import React from 'react'" },
              { line: 2, code: "import './About.css'" },
              { line: 3, code: '' },
              { line: 4, code: 'const About = () => {' },
              { line: 5, code: '  return (' },
              { line: 6, code: "    <div className='about-page'>" },
              { line: 7, code: '      <h1>关于我们</h1>' },
              { line: 8, code: '      <p>我们是一家致力于提供优质产品的公司。</p>' },
              { line: 9, code: '    </div>' },
              { line: 10, code: '  )' },
              { line: 11, code: '}' },
              { line: 12, code: '' },
              { line: 13, code: 'export default About' },
            ],
          },
        ],
      },
      {
        name: 'utils',
        type: 'directory',
        path: 'src/utils',
        children: [
          {
            name: 'format.js',
            type: 'file',
            path: 'src/utils/format.js',
            coverage: { statements: 95, branches: 88, functions: 100, lines: 96 },
            uncoveredLines: [12, 34],
            lines: [
              { line: 1, code: "export function formatNumber(num, decimals = 2) {" },
              { line: 2, code: '  if (typeof num !== "number" || isNaN(num)) return "0"' },
              { line: 3, code: '  return num.toFixed(decimals)' },
              { line: 4, code: '}' },
              { line: 5, code: '' },
              { line: 6, code: "export function formatDate(date, format = 'YYYY-MM-DD') {" },
              { line: 7, code: '  const d = new Date(date)' },
              { line: 8, code: "  const year = d.getFullYear()" },
              { line: 9, code: "  const month = String(d.getMonth() + 1).padStart(2, '0')" },
              { line: 10, code: "  const day = String(d.getDate()).padStart(2, '0')" },
              { line: 11, code: "  return format.replace('YYYY', year).replace('MM', month).replace('DD', day)" },
              { line: 12, code: '}' },
              { line: 13, code: '' },
              { line: 14, code: 'export function formatCurrency(amount, currency = "CNY") {' },
              { line: 15, code: '  return new Intl.NumberFormat("zh-CN", {' },
              { line: 16, code: '    style: "currency",' },
              { line: 17, code: '    currency,' },
              { line: 18, code: '  }).format(amount)' },
              { line: 19, code: '}' },
            ],
          },
          {
            name: 'storage.js',
            type: 'file',
            path: 'src/utils/storage.js',
            coverage: { statements: 55, branches: 40, functions: 60, lines: 58 },
            uncoveredLines: [5, 12, 18, 25, 32, 38, 45],
            lines: [
              { line: 1, code: 'const PREFIX = "app_"' },
              { line: 2, code: '' },
              { line: 3, code: 'export function setItem(key, value) {' },
              { line: 4, code: '  try {' },
              { line: 5, code: '    localStorage.setItem(PREFIX + key, JSON.stringify(value))' },
              { line: 6, code: '    return true' },
              { line: 7, code: '  } catch (e) {' },
              { line: 8, code: '    return false' },
              { line: 9, code: '  }' },
              { line: 10, code: '}' },
              { line: 11, code: '' },
              { line: 12, code: 'export function getItem(key, defaultValue = null) {' },
              { line: 13, code: '  try {' },
              { line: 14, code: '    const value = localStorage.getItem(PREFIX + key)' },
              { line: 15, code: '    return value ? JSON.parse(value) : defaultValue' },
              { line: 16, code: '  } catch (e) {' },
              { line: 17, code: '    return defaultValue' },
              { line: 18, code: '  }' },
              { line: 19, code: '}' },
              { line: 20, code: '' },
              { line: 21, code: 'export function removeItem(key) {' },
              { line: 22, code: '  try {' },
              { line: 23, code: '    localStorage.removeItem(PREFIX + key)' },
              { line: 24, code: '    return true' },
              { line: 25, code: '  } catch (e) {' },
              { line: 26, code: '    return false' },
              { line: 27, code: '  }' },
              { line: 28, code: '}' },
            ],
          },
          {
            name: 'validate.js',
            type: 'file',
            path: 'src/utils/validate.js',
            coverage: { statements: 72, branches: 58, functions: 75, lines: 70 },
            uncoveredLines: [3, 8, 15, 22, 29, 36, 43],
            lines: [
              { line: 1, code: "export function isEmail(email) {" },
              { line: 2, code: '  const regex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/' },
              { line: 3, code: '  return regex.test(email)' },
              { line: 4, code: '}' },
              { line: 5, code: '' },
              { line: 6, code: "export function isPhone(phone) {" },
              { line: 7, code: "  const regex = /^1[3-9]\\d{9}$/" },
              { line: 8, code: '  return regex.test(phone)' },
              { line: 9, code: '}' },
              { line: 10, code: '' },
              { line: 11, code: "export function isRequired(value) {" },
              { line: 12, code: '  if (value === null || value === undefined) return false' },
              { line: 13, code: "  if (typeof value === 'string') return value.trim().length > 0" },
              { line: 14, code: '  return true' },
              { line: 15, code: '}' },
              { line: 16, code: '' },
              { line: 17, code: 'export function minLength(value, min) {' },
              { line: 18, code: "  if (!value) return false" },
              { line: 19, code: "  return value.length >= min" },
              { line: 20, code: '}' },
            ],
          },
        ],
      },
      {
        name: 'api',
        type: 'directory',
        path: 'src/api',
        children: [
          {
            name: 'index.js',
            type: 'file',
            path: 'src/api/index.js',
            coverage: { statements: 0, branches: 0, functions: 0, lines: 0 },
            uncoveredLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            lines: [
              { line: 1, code: "import axios from 'axios'" },
              { line: 2, code: '' },
              { line: 3, code: "const api = axios.create({" },
              { line: 4, code: "  baseURL: '/api'," },
              { line: 5, code: '  timeout: 10000,' },
              { line: 6, code: '})' },
              { line: 7, code: '' },
              { line: 8, code: 'api.interceptors.request.use((config) => {' },
              { line: 9, code: "  const token = localStorage.getItem('token')" },
              { line: 10, code: '  if (token) {' },
              { line: 11, code: "    config.headers.Authorization = `Bearer ${token}`" },
              { line: 12, code: '  }' },
              { line: 13, code: '  return config' },
              { line: 14, code: '})' },
              { line: 15, code: '' },
              { line: 16, code: 'export default api' },
            ],
          },
          {
            name: 'user.js',
            type: 'file',
            path: 'src/api/user.js',
            coverage: { statements: 30, branches: 20, functions: 25, lines: 35 },
            uncoveredLines: [5, 10, 15, 20, 25, 30, 35, 40, 45],
            lines: [
              { line: 1, code: "import api from './index'" },
              { line: 2, code: '' },
              { line: 3, code: 'export function login(data) {' },
              { line: 4, code: "  return api.post('/auth/login', data)" },
              { line: 5, code: '}' },
              { line: 6, code: '' },
              { line: 7, code: 'export function register(data) {' },
              { line: 8, code: "  return api.post('/auth/register', data)" },
              { line: 9, code: '}' },
              { line: 10, code: '' },
              { line: 11, code: 'export function getUserInfo() {' },
              { line: 12, code: "  return api.get('/user/info')" },
              { line: 13, code: '}' },
              { line: 14, code: '' },
              { line: 15, code: 'export function updateUserInfo(data) {' },
              { line: 16, code: "  return api.put('/user/info', data)" },
              { line: 17, code: '}' },
              { line: 18, code: '' },
              { line: 19, code: 'export function changePassword(data) {' },
              { line: 20, code: "  return api.post('/user/password', data)" },
              { line: 21, code: '}' },
            ],
          },
        ],
      },
      {
        name: 'hooks',
        type: 'directory',
        path: 'src/hooks',
        children: [
          {
            name: 'useDebounce.js',
            type: 'file',
            path: 'src/hooks/useDebounce.js',
            coverage: { statements: 45, branches: 35, functions: 50, lines: 42 },
            uncoveredLines: [5, 10, 15, 20, 25],
            lines: [
              { line: 1, code: "import { useState, useEffect } from 'react'" },
              { line: 2, code: '' },
              { line: 3, code: 'function useDebounce(value, delay = 300) {' },
              { line: 4, code: "  const [debouncedValue, setDebouncedValue] = useState(value)" },
              { line: 5, code: '' },
              { line: 6, code: '  useEffect(() => {' },
              { line: 7, code: '    const handler = setTimeout(() => {' },
              { line: 8, code: '      setDebouncedValue(value)' },
              { line: 9, code: '    }, delay)' },
              { line: 10, code: '' },
              { line: 11, code: '    return () => {' },
              { line: 12, code: '      clearTimeout(handler)' },
              { line: 13, code: '    }' },
              { line: 14, code: '  }, [value, delay])' },
              { line: 15, code: '' },
              { line: 16, code: '  return debouncedValue' },
              { line: 17, code: '}' },
              { line: 18, code: '' },
              { line: 19, code: 'export default useDebounce' },
            ],
          },
          {
            name: 'useLocalStorage.js',
            type: 'file',
            path: 'src/hooks/useLocalStorage.js',
            coverage: { statements: 38, branches: 28, functions: 40, lines: 35 },
            uncoveredLines: [5, 10, 15, 20, 25, 30],
            lines: [
              { line: 1, code: "import { useState } from 'react'" },
              { line: 2, code: '' },
              { line: 3, code: 'function useLocalStorage(key, initialValue) {' },
              { line: 4, code: '  const [storedValue, setStoredValue] = useState(() => {' },
              { line: 5, code: '    try {' },
              { line: 6, code: '      const item = localStorage.getItem(key)' },
              { line: 7, code: '      return item ? JSON.parse(item) : initialValue' },
              { line: 8, code: '    } catch (error) {' },
              { line: 9, code: '      return initialValue' },
              { line: 10, code: '    }' },
              { line: 11, code: '  })' },
              { line: 12, code: '' },
              { line: 13, code: '  const setValue = (value) => {' },
              { line: 14, code: '    try {' },
              { line: 15, code: '      const valueToStore = value instanceof Function ? value(storedValue) : value' },
              { line: 16, code: '      setStoredValue(valueToStore)' },
              { line: 17, code: '      localStorage.setItem(key, JSON.stringify(valueToStore))' },
              { line: 18, code: '    } catch (error) {' },
              { line: 19, code: '      console.error(error)' },
              { line: 20, code: '    }' },
              { line: 21, code: '  }' },
              { line: 22, code: '' },
              { line: 23, code: '  return [storedValue, setValue]' },
              { line: 24, code: '}' },
              { line: 25, code: '' },
              { line: 26, code: 'export default useLocalStorage' },
            ],
          },
        ],
      },
      {
        name: 'App.jsx',
        type: 'file',
        path: 'src/App.jsx',
        coverage: { statements: 82, branches: 70, functions: 85, lines: 80 },
        uncoveredLines: [15, 28, 42, 55],
        lines: [
          { line: 1, code: "import React from 'react'" },
          { line: 2, code: "import { BrowserRouter, Routes, Route } from 'react-router-dom'" },
          { line: 3, code: "import './App.css'" },
          { line: 4, code: "import Home from './pages/Home'" },
          { line: 5, code: "import About from './pages/About'" },
          { line: 6, code: "import NotFound from './pages/NotFound'" },
          { line: 7, code: '' },
          { line: 8, code: 'function App() {' },
          { line: 9, code: '  return (' },
          { line: 10, code: '    <BrowserRouter>' },
          { line: 11, code: '      <Routes>' },
          { line: 12, code: '        <Route path="/" element={<Home />} />' },
          { line: 13, code: '        <Route path="/about" element={<About />} />' },
          { line: 14, code: '        <Route path="*" element={<NotFound />} />' },
          { line: 15, code: '      </Routes>' },
          { line: 16, code: '    </BrowserRouter>' },
          { line: 17, code: '  )' },
          { line: 18, code: '}' },
          { line: 19, code: '' },
          { line: 20, code: 'export default App' },
        ],
      },
      {
        name: 'index.jsx',
        type: 'file',
        path: 'src/index.jsx',
        coverage: { statements: 100, branches: 100, functions: 100, lines: 100 },
        uncoveredLines: [],
        lines: [
          { line: 1, code: "import React from 'react'" },
          { line: 2, code: "import ReactDOM from 'react-dom/client'" },
          { line: 3, code: "import './index.css'" },
          { line: 4, code: "import App from './App'" },
          { line: 5, code: '' },
          { line: 6, code: "ReactDOM.createRoot(document.getElementById('root')).render(" },
          { line: 7, code: '  <React.StrictMode>' },
          { line: 8, code: '    <App />' },
          { line: 9, code: '  </React.StrictMode>' },
          { line: 10, code: ')' },
        ],
      },
    ],
  }
}

export function generateMockTrendData() {
  const data = []
  const today = new Date()

  for (let i = TREND_DAYS - 1; i >= 0; i--) {
    const date = new Date(today)
    date.setDate(date.getDate() - i)
    const dateStr = `${date.getMonth() + 1}/${date.getDate()}`

    const baseStatements = 65 + (TREND_DAYS - i) * 0.3
    const baseLines = 62 + (TREND_DAYS - i) * 0.25

    const statements = Math.round((baseStatements + (Math.random() - 0.5) * 5) * 10) / 10
    const lines = Math.round((baseLines + (Math.random() - 0.5) * 4) * 10) / 10

    data.push({
      date: dateStr,
      statements: Math.min(95, Math.max(50, statements)),
      lines: Math.min(95, Math.max(45, lines)),
    })
  }

  return data
}
